version: 2.1

orbs: 
  slack: circleci/slack@4.9.3

executors:
  app-executor:
    docker:
      - image: circleci/node:14.18.1
    working_directory: ~/repo
  
  slack-executor:
    docker:
      - image: 'cimg/base:stable'
  
  terraform-executor: 
    docker:
      - image: hashicorp/terraform:latest

  docker-publisher:
    environment:
      IMAGE_NAME: dibyajyotimishra/infinitemovies
    docker:
      - image: circleci/buildpack-deps:stretch



aliases:
  - &show-current-branch
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install Dependencies
      command: |
        mkdir -p artifacts
        npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}
  - &install-aws-cli
    run:
      name: Installing AWS CLI
      working_directory: /
      command: |
        sudo apt-get -y -qq update
        sudo apt-get -y install awscli
        sudo apt-get install -y python-pip python-dev build-essential
  - &build-project
    run:
      name: Build Project
      command: |
        npm install
        npm run build
        cd build
        zip ../build.zip -r * .[^.]*
        echo "Build Successful !"
 
jobs:
  setup:
   executor: app-executor
   steps:
      - checkout
      - *show-current-branch
      - *restore-cache
      - *install-dependencies
      - *save-cache
      - run:
          name: Copy Terraform folder
          command: cp -r terraform artifacts/terraform/
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch
      - *restore-cache
      - run:
          name: Run Linting
          command: npm run lint

  prettify:
    executor: app-executor
    steps: 
      - checkout
      - *show-current-branch
      - *restore-cache
      - run:
          name: Run Prettier
          command: npm run prettify 

  terraform-validate:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch
      -  run:
          name: Terraform Validate and Format
          command: |
             cd terraform/
             terraform init -backend=false
             terraform validate
            #  terraform fmt -check
  terraform-plan-and-apply:
    executor: terraform-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - *show-current-branch
      -  run:
          name: Terraform Plan
          command: |
             cd artifacts/terraform/
             terraform init
             terraform workspace select ${CIRCLE_BRANCH} || terraform workspace new ${CIRCLE_BRANCH}
             terraform plan
      -  run:
          name: Terraform Apply
          command: |
             cd artifacts/terraform/
             terraform workspace select ${CIRCLE_BRANCH}
             terraform apply --auto-approve 
             terraform output infinite-movies-bucket-name > ../infinite-mvies-bucket-name.txt
             terraform output cloudfront-distribution-id > ../cloudfront-distribution-id.txt
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts 

  deploy-to-heroku:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch
      - run:
          name: Deploy to Heruko
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]
            then git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_DEV_APP}.git ${CIRCLE_BRANCH}
            fi 

  publish-to-dockerhub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - *restore-cache
      - run: docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}"
      - run: docker build -t ${IMAGE_NAME}:latest .
      - run: 
          name: Tag and Push to docker hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then 
              docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${CIRCLE_BUILD_NUM}-production && docker push ${IMAGE_NAME}:@${CIRCLE_BUILD_NUM}-production 
            fi

  
  deploy-to-aws-s3:
    executor: app-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - *show-current-branch
      - *install-aws-cli
      - *build-project
      - run:
          name: Deploy to AWS S3
          command: | 
            AWS_BUCKET_NAME=$(cat artifacts/infinite-mvies-bucket-name.txt | sed 's/\"//g')
            echo $AWS_BUCKET_NAME
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then 
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_NAME} --delete
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then 
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_NAME} --delete
            fi
  
  deploy-to-aws-cloudfront:
    executor: app-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - *show-current-branch
      - *install-aws-cli
      - *build-project
      - run:
          name: Deploy to AWS CloudFront
          command: |
            AWS_CLOUDFRONT_DISTRIBUTION_ID=$(cat artifacts/cloudfront-distribution-id.txt | sed 's/\"//g')
            echo $AWS_CLOUDFRONT_DISTRIBUTION_ID
            aws configure set preview.cloudfront true
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then 
              aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID} --path /\*
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then 
              aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID} --path /\*
            fi
  
  send-notification:
    executor: slack-executor
    steps:
      - run: echo "Sending Notification to Slack Channel"
      - slack/notify:
          event: 'pass'
          channel: 'infinite-movies'
          template: ''
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Hurray 🎉 !!! Deployed ${CIRCLE_BRANCH} on servers!",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n$CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Deployed at:*\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build Number:*\n$CIRCLE_BUILD_NUM"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n$CIRCLE_PROJECT_USERNAME"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"  
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Project"  
                      },
                      "url": "https://github.com/DibyajyotiMishra/InfiniteMovies"
                    }
                  ]
                }
              ]  
            }
      - slack/notify:
          event: 'fail'
          mentions: '@dibyajyotimishra14'
          template: basic_fail_1

  terraform-destroy:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch
      - run: 
          name: Terraform Destroy
          command: |
            cd terraform/
            terraform init
            terraform workspace select ${CIRCLE_BRANCH} || terraform workspace new ${CIRCLE_BRANCH} 
            terraform destroy --auto-approve
 
workflows:
  build_and_deploy:
    jobs:
      - setup
      - linting:
          requires:
            - setup
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - prettify:
          requires:
            - setup
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - terraform-validate:
          requires:
            - linting
            - prettify
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - terraform-plan-and-apply:
          requires:
            - terraform-validate
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - publish-to-docker-hub:
          requires:
            - terraform-plan-and-apply
          filters:
            branches:
              only:
                - master
      - deploy-to-aws-s3:
          requires:
            - terraform-plan-and-apply
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deploy-to-aws-cloudfront:
          requires:
            - deploy-to-aws-s3
          filters:
            branches:
              only: 
                - develop              
                - staging
                - master
      - send-notification:
          requires:
            - deploy-to-aws-cloudfront
          filters:
            branches:
              only:
                - develop               
                - staging
                - master

      - hold:
          type: approval
          requires:
            - send-notification

      - terraform-destroy:
          requires:
            - hold
          filters:
            branches:
              only:
                - develop
                - staging
                - master

