const MovieActionTypes = {
  MOVIES_LIST: 'MOVIES_LIST',
  SET_ERROR: 'SET_ERROR',
  RESPONSE_PAGE: 'RESPONSE_PAGE',
  LOAD_MORE_MOVIES: 'LOAD_MORE_MOVIES',
  MOVIE_TYPE: 'MOVIE_TYPE',
};

export default MovieActionTypes;
